-- ==============================================================================
-- NAGARDRISHTI — MIGRATION 001: EXTENSIONS & ENUMS
-- Madhya Pradesh Geospatial Civic Intelligence and Feedback Analytics Platform
-- ==============================================================================

-- 1. Enable Required Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "btree_gist";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- 2. Enumerated Types

-- Administrative unit types across Madhya Pradesh
DO $$ BEGIN
    CREATE TYPE admin_unit_type AS ENUM (
        'state',
        'division',
        'district',
        'subdivision',
        'tehsil',
        'block',
        'ulb',
        'ward',
        'gram_panchayat',
        'village',
        'locality'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- ULB / Municipality classifications in MP
DO $$ BEGIN
    CREATE TYPE ulb_type AS ENUM (
        'nagar_nigam',         -- Municipal Corporation (e.g., Gwalior, Indore, Bhopal)
        'nagar_palika_parishad', -- Municipality
        'nagar_parishad',      -- Town Council
        'cantonment_board'     -- Cantonment
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Data Source Authority Levels
DO $$ BEGIN
    CREATE TYPE source_authority_level AS ENUM (
        'verified_state_government',  -- e.g., GARUD MP, MP eService, UADD
        'verified_central_government',-- e.g., ISRO Bhuvan, CPCB, data.gov.in
        'verified_municipal',         -- e.g., Gwalior Municipal Corporation (GMC)
        'conditional_official',       -- Official, pending API/WFS credential clearance
        'community_open',             -- OpenStreetMap, WikiData
        'internal_platform'           -- Generated by NagarDrishti (reports, clusters)
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- GIS Layer Source Types
DO $$ BEGIN
    CREATE TYPE layer_source_type AS ENUM (
        'internal_postgis', -- Stored in gis_features table
        'geojson',          -- Hosted / proxied GeoJSON
        'vector_tiles',     -- Mapbox / OpenMapTiles / MVT endpoint
        'wms',              -- OGC Web Map Service (e.g. Bhuvan)
        'wmts',             -- OGC Web Map Tile Service
        'external_api',     -- Dynamic API adapter
        'uploaded_dataset'  -- User/admin uploaded dataset
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- PostGIS Geometry Representation Types
DO $$ BEGIN
    CREATE TYPE gis_geometry_type AS ENUM (
        'POINT',
        'MULTIPOINT',
        'LINESTRING',
        'MULTILINESTRING',
        'POLYGON',
        'MULTIPOLYGON',
        'GEOMETRYCOLLECTION'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Citizen Feedback Statuses (SRS Section 4.4 & 21.3)
DO $$ BEGIN
    CREATE TYPE report_status AS ENUM (
        'submitted',              -- Initial citizen submission
        'ai_processed',           -- Sarvam transcribed, language normalized & categorized
        'duplicate_clustered',    -- Clustered into an existing spatial/temporal issue
        'community_corroborated', -- Multiple citizens validated the issue
        'needs_review',           -- Flagged for moderator/verifier manual attention
        'verified',               -- Verified by department/analyst/evidence
        'in_progress',            -- Department has scheduled or is performing work
        'resolved',               -- Issue resolved with closure evidence
        'rejected_spam'           -- Abusive, duplicate spam or invalid submission
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Report Media Types
DO $$ BEGIN
    CREATE TYPE media_type AS ENUM (
        'image',
        'audio',
        'video',
        'document'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Evidence Provenance Types
DO $$ BEGIN
    CREATE TYPE evidence_type AS ENUM (
        'citizen_submission',
        'official_dataset',
        'government_notice',
        'trusted_public_mention',
        'analyst_verification',
        'sensor_telemetry'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- User Roles (SRS Section 3)
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM (
        'guest',
        'citizen',
        'analyst',
        'verifier',
        'gis_admin',
        'super_admin'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Ingestion Run Statuses
DO $$ BEGIN
    CREATE TYPE ingestion_status AS ENUM (
        'pending',
        'running',
        'completed',
        'partial_failure',
        'failed'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Automated Updated_At Trigger Function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
